# Generated by Django 5.2.9 on 2025-12-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Университет аты')),
                ('full_name', models.CharField(max_length=300, verbose_name='Толық аты')),
                ('city', models.CharField(max_length=100, verbose_name='Қала')),
                ('overall_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B')], default='B', max_length=5)),
                ('min_ent', models.IntegerField(default=50, verbose_name='Мин. ЕНТ')),
                ('max_ent', models.IntegerField(default=140, verbose_name='Макс. ЕНТ')),
                ('min_tuition', models.IntegerField(verbose_name='Оқу құны (мин)')),
                ('max_tuition', models.IntegerField(verbose_name='Оқу құны (макс)')),
                ('has_grant', models.BooleanField(default=True, verbose_name='Грант бар')),
                ('has_military', models.BooleanField(default=False, verbose_name='Военная кафедра')),
                ('has_dormitory', models.BooleanField(default=True, verbose_name='Жатақхана')),
                ('lat', models.FloatField(verbose_name='Ендік (Lat)')),
                ('lng', models.FloatField(verbose_name='Бойлық (Lng)')),
                ('image_url', models.URLField(blank=True, verbose_name='Сурет сілтемесі')),
            ],
        ),
    ]
