# Generated by Django 5.2.9 on 2025-12-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='has_dormitory',
        ),
        migrations.RemoveField(
            model_name='university',
            name='has_grant',
        ),
        migrations.RemoveField(
            model_name='university',
            name='has_military',
        ),
        migrations.RemoveField(
            model_name='university',
            name='max_ent',
        ),
        migrations.RemoveField(
            model_name='university',
            name='max_tuition',
        ),
        migrations.RemoveField(
            model_name='university',
            name='min_tuition',
        ),
        migrations.AddField(
            model_name='university',
            name='chance',
            field=models.CharField(default='Высокий', max_length=50, verbose_name='Түсу ықтималдығы'),
        ),
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.URLField(blank=True, default='https://placehold.co/100', verbose_name='Логотип URL'),
        ),
        migrations.AddField(
            model_name='university',
            name='tags',
            field=models.CharField(default='IT, Инженерия', max_length=200, verbose_name='Тегтер (үтірмен)'),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition',
            field=models.CharField(default='1.0-2.0 млн ₸', max_length=100, verbose_name='Құны (млн ₸)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Кампус суреті'),
        ),
        migrations.AlterField(
            model_name='university',
            name='min_ent',
            field=models.IntegerField(default=50, verbose_name='Орташа ЕНТ'),
        ),
        migrations.AlterField(
            model_name='university',
            name='overall_grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+')], default='A', max_length=5),
        ),
    ]
